version: '3.8'

services:
  edi-service:
    build: .
    ports:
      - "50051:50051"
    environment:
      - EDI_SERVICE_HOST=0.0.0.0
      - EDI_SERVICE_PORT=50051
      - EDI_LOG_LEVEL=INFO
      - EDI_VALIDATION_STRICT=true
    volumes:
      - ../proto:/proto:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; grpc.channel_ready_future(grpc.insecure_channel('localhost:50051')).result(timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  edi-client-test:
    build: .
    command: python examples/client_example.py
    depends_on:
      - edi-service
    environment:
      - EDI_SERVICE_HOST=edi-service
      - EDI_SERVICE_PORT=50051
    volumes:
      - ../proto:/proto:ro
    profiles:
      - testing
